[package]
name = "cel-interpreter"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cel-parser = { path = "../parser" }
serde = {version = "1.0.171", features = ["derive"]}
